import { 
  ItemCategory, 
  SchoolLocation, 
  UserProfile, 
  Item, 
  IntegrityScenario,
  SchoolActivity,
  ActivityBadge,
  ActivitySubmission
} from '@/types';

export const CATEGORIES: { id: ItemCategory; label: string; icon: string; description: string }[] = [
  { id: 'electronics', label: 'إلكترونيات وأجهزة', icon: 'Laptop', description: 'حاسبات، سماعات، ساعات، شواحن' },
  { id: 'books', label: 'كتب ودفاتر ومذكرات', icon: 'BookOpen', description: 'كتب دراسية، دفاتر ملاحظات، ملفات' },
  { id: 'stationery', label: 'أدوات مدرسية', icon: 'PenTool', description: 'مقالم، أقلام، علب هندسة، مساطر' },
  { id: 'bottles', label: 'قوارير وحافظات ماء', icon: 'CupSoda', description: 'مطارات ماء، حافظات سوائل' },
  { id: 'keys', label: 'مفاتيح وميداليات', icon: 'KeyRound', description: 'مفاتيح منازل، خزائن، سيارات' },
  { id: 'bags', label: 'حقائب وأكياس', icon: 'ShoppingBag', description: 'حقائب ظهر، حقائب رياضية' },
  { id: 'clothing', label: 'ملابس وأزياء', icon: 'Shirt', description: 'سترات، جاكيتات، قبعات' },
  { id: 'wallets_cards', label: 'بطاقات ومحافظ', icon: 'CreditCard', description: 'بطاقة مدرسية، بطاقة صراف، محافظ' },
  { id: 'sports', label: 'أدوات رياضية', icon: 'Trophy', description: 'كرات، ألبسة رياضية، أحذية' },
  { id: 'personal', label: 'أغراض شخصية أخرى', icon: 'FolderOpen', description: 'نظارات، ساعات، إكسسوارات' },
];

export const SCHOOL_LOCATIONS: SchoolLocation[] = [
  { id: 'science_lab', name: 'معمل العلوم والكيمياء', building: 'المبنى العلمي', floor: 'الطابق الثاني', icon: 'FlaskConical' },
  { id: 'library', name: 'المكتبة المدرسية', building: 'المبنى الرئيسي', floor: 'الطابق الأول', icon: 'Library' },
  { id: 'cafeteria', name: 'الكافتيريا / صالة الطعام', building: 'مبنى الخدمات', floor: 'الطابق الأرضي', icon: 'Utensils' },
  { id: 'gym', name: 'الصالة الرياضية المغلقة', building: 'المجمع الرياضي', floor: 'الطابق الأرضي', icon: 'Dumbbell' },
  { id: 'playground', name: 'الملعب والساحة الخارجية', building: 'الساحة المركزية', floor: 'خارجي', icon: 'Sun' },
  { id: 'classrooms_g1', name: 'فصول المرحلة الأولى (10 - 11)', building: 'المبنى الأكاديمي أ', floor: 'الطابق الأول', icon: 'GraduationCap' },
  { id: 'classrooms_g2', name: 'فصول المرحلة الثانية (12)', building: 'المبنى الأكاديمي ب', floor: 'الطابق الثاني', icon: 'Building' },
  { id: 'computer_lab', name: 'معمل الحاسب الآلي والتقنية', building: 'المبنى العلمي', floor: 'الطابق الأول', icon: 'Monitor' },
  { id: 'admin_office', name: 'مكتب الإدارة والأمانات', building: 'المبنى الرئيسي', floor: 'الطابق الأرضي', icon: 'ShieldCheck' },
  { id: 'prayer_room', name: 'المصلى المدرسي', building: 'المبنى الرئيسي', floor: 'الطابق الأرضي', icon: 'Moon' },
];

export const ITEM_COLORS = [
  { name: 'أسود', hex: '#18181B' },
  { name: 'أزرق', hex: '#2563EB' },
  { name: 'فضي / رمادي', hex: '#64748B' },
  { name: 'أبيض', hex: '#F8FAFC' },
  { name: 'كحلي', hex: '#1E293B' },
  { name: 'أخضر', hex: '#16A34A' },
  { name: 'أحمر', hex: '#DC2626' },
  { name: 'بني', hex: '#78350F' },
  { name: 'أخرى', hex: '#8B5CF6' },
];

// PRIMARY DEMO IDENTITIES AND LEADERBOARD ROSTER
export const DEMO_USERS: UserProfile[] = [
  {
    id: 'user_malak',
    name: 'ملك محمد فروق',
    email: 'malak.farouk@school.edu',
    role: 'student',
    grade: 'الصف الحادي عشر - علمي',
    avatar: '',
    returnedCount: 2,
    isTrusted: true,
    goodwillPoints: 100,
  },
  {
    id: 'user_moshira',
    name: 'أ/ مشيرة محمد',
    email: 'moshira.admin@school.edu',
    role: 'admin',
    grade: 'مديرة المدرسة ورئيسة لجنة الأمانات',
    avatar: '',
    returnedCount: 34,
    isTrusted: true,
    goodwillPoints: 0,
  },
  {
    id: 'student_finder_sara',
    name: 'سارة القحطاني',
    email: 'sara.q@school.edu',
    role: 'student',
    grade: 'الصف العاشر - أ',
    avatar: '',
    returnedCount: 3,
    isTrusted: true,
    goodwillPoints: 90,
  },
  {
    id: 'student_khalid',
    name: 'خالد الدوسري',
    email: 'khalid.d@school.edu',
    role: 'student',
    grade: 'الصف الثاني عشر - علمي',
    avatar: '',
    returnedCount: 2,
    isTrusted: true,
    goodwillPoints: 80,
  },
  {
    id: 'student_reem',
    name: 'ريم الغامدي',
    email: 'reem.g@school.edu',
    role: 'student',
    grade: 'الصف الحادي عشر - علمي',
    avatar: '',
    returnedCount: 2,
    isTrusted: true,
    goodwillPoints: 70,
  },
  {
    id: 'student_fahad',
    name: 'فهد المطيري',
    email: 'fahad.m@school.edu',
    role: 'student',
    grade: 'الصف العاشر - ب',
    avatar: '',
    returnedCount: 1,
    isTrusted: true,
    goodwillPoints: 50,
  },
  {
    id: 'student_nour',
    name: 'نور العتيبي',
    email: 'nour.o@school.edu',
    role: 'student',
    grade: 'الصف الثاني عشر - أدبي',
    avatar: '',
    returnedCount: 1,
    isTrusted: true,
    goodwillPoints: 40,
  },
  {
    id: 'student_omar',
    name: 'عمر التميمي',
    email: 'omar.t@school.edu',
    role: 'student',
    grade: 'الصف العاشر - ب',
    avatar: '',
    returnedCount: 0,
    isTrusted: false,
    goodwillPoints: 20,
  },
];

export const INITIAL_NOTIFICATIONS = [
  {
    id: 'notif_match_calc',
    title: '🎯 تطابق ذكي بنسبة 88%',
    message: 'تم العثور على حاسبة كاسيو سوداء مطابقة لمواصفات بلاغك في معمل العلوم والكيمياء!',
    type: 'match' as const,
    timestamp: '2026-08-29T18:46:00.000Z',
    isRead: false,
    linkUrl: '/match/item_malak_lost_calc',
  },
  {
    id: 'notif_claim_pin',
    title: '📜 اعتماد استرداد أمانة جاهزة',
    message: 'تمت الموافقة على طلب استرداد غرضك، استخدم رمز التسليم (4826) عند الاستلام من الإدارة.',
    type: 'claim' as const,
    timestamp: '2026-08-29T19:00:00.000Z',
    isRead: false,
    linkUrl: '/my-items',
  },
  {
    id: 'notif_points_silver',
    title: '🌟 وسام سفير النزاهة الفضي',
    message: 'مبروك! جمعت 100 نقطة أمانة وترقيت إلى رتبة سفير فضي معتمد في المدرسة.',
    type: 'points' as const,
    timestamp: '2026-08-29T17:30:00.000Z',
    isRead: true,
    linkUrl: '/profile',
  },
  {
    id: 'notif_integrity_challenge',
    title: '🏆 انطلاق التحدي الأسبوعي للأمانة',
    message: '5 مواقف جديدة بانتظارك هذا الأسبوع لاختبار نزاهتك وكسب نقاط التميز الأخلاقي.',
    type: 'integrity' as const,
    timestamp: '2026-08-29T12:00:00.000Z',
    isRead: true,
    linkUrl: '/integrity',
  },
];

// DETERMINISTIC DEMO ITEMS WITH FIXED ISO TIMESTAMPS
export const INITIAL_SEED_ITEMS: Item[] = [
  // 1. MALAK'S LOST ITEM (Target for 88% Match demo!)
  {
    id: 'item_malak_lost_calc',
    title: 'حاسبة كاسيو علمية fx-991EX',
    type: 'lost',
    category: 'electronics',
    locationId: 'science_lab',
    locationDetails: 'نسيتها على طاولة التجارب رقم 3 في معمل الكيمياء بعد الحصة الرابعة',
    date: '2026-08-29T18:00:00.000Z',
    color: 'أسود',
    brand: 'Casio',
    description: 'حاسبة علمية سوداء مع غطاء حماية وعليها ملصق كوكب زحل الأزرق بالخلف.',
    status: 'open',
    reportedBy: DEMO_USERS[0], // Malak
    createdAt: '2026-08-29T18:00:00.000Z',
  },

  // 2. MATCHING FOUND ITEM IN SCIENCE LAB (88% Match with Malak's Calculator!)
  {
    id: 'item_found_calc_lab',
    title: 'آلة حاسبة Casio سوداء',
    type: 'found',
    category: 'electronics',
    locationId: 'science_lab',
    locationDetails: 'وُجدت في معمل الكيمياء على طاولة التجارب بجانب المجهر',
    date: '2026-08-29T18:45:00.000Z',
    color: 'أسود',
    brand: 'Casio',
    description: 'آلة حاسبة علمية سوداء كاسيو بحالة ممتازة ومقفلة بغطائها الأصلي.',
    secretQuestion: 'ما هو شكل ولون الملصق الموجود على الغطاء الخلفي للحاسبة؟',
    secretAnswer: 'ملصق أزرق دائري لكوكب زحل',
    custody: 'with_finder',
    status: 'open',
    reportedBy: {
      id: 'student_finder_sara',
      name: 'سارة القحطاني',
      email: 'sara.q@school.edu',
      role: 'student',
      grade: 'الصف العاشر - أ',
      avatar: '',
      returnedCount: 3,
      isTrusted: true,
      goodwillPoints: 90,
    },
    createdAt: '2026-08-29T18:45:00.000Z',
  },

  // 3. MALAK'S LOST WATER BOTTLE
  {
    id: 'item_malak_lost_bottle',
    title: 'قارورة ماء رياضية زرقاء Hydro Flask',
    type: 'lost',
    category: 'bottles',
    locationId: 'gym',
    locationDetails: 'عند مقاعد البدلاء في الصالة الرياضية أثناء حصة التربية البدنية',
    date: '2026-08-29T15:30:00.000Z',
    color: 'أزرق',
    brand: 'Hydro Flask',
    description: 'مطارة ماء زرقاء سعة 750 مل مع حزام غطاء مطاطي أسود.',
    status: 'open',
    reportedBy: DEMO_USERS[0], // Malak
    createdAt: '2026-08-29T15:30:00.000Z',
  },

  // 4. MALAK'S REUNITED NOTEBOOK (Demonstrating Reunited History)
  {
    id: 'item_malak_reunited_notebook',
    title: 'دفتر مذكرات الرياضيات المتقدمة',
    type: 'lost',
    category: 'books',
    locationId: 'classrooms_g1',
    locationDetails: 'الفصل 11-أ علمي',
    date: '2026-08-27T08:00:00.000Z',
    color: 'بني',
    description: 'دفتر بغلاف بني مقوى يحتوي على مسائل وحلول تفاضل وتكامل.',
    status: 'reunited',
    reunitedAt: '2026-08-28T10:00:00.000Z',
    reportedBy: DEMO_USERS[0], // Malak
    createdAt: '2026-08-27T08:00:00.000Z',
  },

  // 5. FOUND WIRELESS EARBUDS
  {
    id: 'item_found_airpods',
    title: 'سماعات Apple AirPods Pro لاسلكية',
    type: 'found',
    category: 'electronics',
    locationId: 'library',
    locationDetails: 'في ركن القراءة الهادئة بالطابق الأول بجانب النافذة',
    date: '2026-08-29T16:30:00.000Z',
    color: 'أبيض',
    brand: 'Apple',
    description: 'علبة سماعات آيربودز بيضاء نظيفة بجراب سيليكون شفاف.',
    secretQuestion: 'ما هو النقش أو الرسمة الصغيرة على جراب السماعات؟',
    secretAnswer: 'رسمة شمس صغيرة باللون الأصفر',
    custody: 'at_office',
    status: 'open',
    reportedBy: DEMO_USERS[1], // Moshira Admin
    createdAt: '2026-08-29T16:30:00.000Z',
  },

  // 6. FOUND SILVER WATCH
  {
    id: 'item_found_watch',
    title: 'ساعة يد فضية كلاسيكية',
    type: 'found',
    category: 'personal',
    locationId: 'playground',
    locationDetails: 'قرب مدخل الملعب الرياضي',
    date: '2026-08-28T11:00:00.000Z',
    color: 'فضي / رمادي',
    description: 'ساعة يد بسوار ستانلس ستيل ومينا داكن وعقارب زرقاء.',
    secretQuestion: 'ما هو لون المينا الداخلي للساعة؟',
    secretAnswer: 'كحلي داكن',
    custody: 'at_office',
    status: 'open',
    reportedBy: DEMO_USERS[1], // Moshira Admin
    createdAt: '2026-08-28T11:00:00.000Z',
  },

  // 7. FOUND HOUSE KEYS
  {
    id: 'item_found_keys',
    title: 'مفاتيح منزل مع ميدالية جلدية بنية',
    type: 'found',
    category: 'keys',
    locationId: 'cafeteria',
    locationDetails: 'على طاولة الطعام رقم 12 في الكافتيريا',
    date: '2026-08-29T13:00:00.000Z',
    color: 'بني',
    description: 'حلقة مفاتيح تضم مفتاحين أحدهما فضي والآخر نحاسي مع قطعة جلد.',
    secretQuestion: 'كم عدد المفاتيح وما لون القطعة الجلدية؟',
    secretAnswer: 'مفتاحين وميدالية بنية',
    custody: 'at_office',
    status: 'reunited',
    reunitedAt: '2026-08-29T16:00:00.000Z',
    reportedBy: DEMO_USERS[1], // Moshira
    createdAt: '2026-08-29T13:00:00.000Z',
  },

  // 8. LOST PENCIL CASE
  {
    id: 'item_lost_pencil_case',
    title: 'مقلمة مدرسية كحلية بسحاب برتقالي',
    type: 'lost',
    category: 'stationery',
    locationId: 'classrooms_g1',
    locationDetails: 'في فصل 10-ب تحت المقعد الثاني',
    date: '2026-08-29T12:00:00.000Z',
    color: 'كحلي',
    description: 'مقلمة قماشية تضم أقلام رصاص وألوان مائية ومسطرة 20 سم.',
    status: 'open',
    reportedBy: {
      id: 'student_omar',
      name: 'عمر التميمي',
      email: 'omar.t@school.edu',
      role: 'student',
      grade: 'الصف العاشر - ب',
      avatar: '',
      returnedCount: 0,
      isTrusted: false,
      goodwillPoints: 10,
    },
    createdAt: '2026-08-29T12:00:00.000Z',
  },

  // 9. FOUND BACKPACK
  {
    id: 'item_found_backpack',
    title: 'حقيبة ظهر مدرسية سوداء',
    type: 'found',
    category: 'bags',
    locationId: 'prayer_room',
    locationDetails: 'عند رف الأحذية في المصلى المدرسي',
    date: '2026-08-28T14:00:00.000Z',
    color: 'أسود',
    description: 'حقيبة ظهر مقاس متوسط بها جيوب جانبية لمطارة الماء.',
    secretQuestion: 'ما اسم الكتاب الموجود داخل الجيب الرئيسي؟',
    secretAnswer: 'كتاب الأحياء للصف الحادي عشر',
    custody: 'at_office',
    status: 'open',
    reportedBy: DEMO_USERS[1], // Moshira
    createdAt: '2026-08-28T14:00:00.000Z',
  },

  // 10. FOUND USB DRIVE
  {
    id: 'item_found_usb',
    title: 'ذاكرة فلاش USB سعة 64GB',
    type: 'found',
    category: 'electronics',
    locationId: 'computer_lab',
    locationDetails: 'مركبة في جهاز الحاسوب رقم 7 في معمل التقنية',
    date: '2026-08-29T14:30:00.000Z',
    color: 'أخضر',
    brand: 'SanDisk',
    description: 'فلاش ميموري بلون أخضر زمردي وهيكل معدني.',
    secretQuestion: 'ما اسم المجلد الرئيسي داخل الفلاش؟',
    secretAnswer: 'مشروع التخرج 2026',
    custody: 'with_finder',
    status: 'open',
    reportedBy: {
      id: 'student_finder_sara',
      name: 'سارة القحطاني',
      email: 'sara.q@school.edu',
      role: 'student',
      grade: 'الصف العاشر - أ',
      avatar: '',
      returnedCount: 3,
      isTrusted: true,
      goodwillPoints: 90,
    },
    createdAt: '2026-08-29T14:30:00.000Z',
  },

  // 11. FOUND SCHOOL ID
  {
    id: 'item_found_school_id',
    title: 'بطاقة هوية مدرسية ذكية للطالب فهد',
    type: 'found',
    category: 'wallets_cards',
    locationId: 'cafeteria',
    locationDetails: 'قرب ماكينة الدفع في الكافتيريا',
    date: '2026-08-29T17:00:00.000Z',
    color: 'أبيض',
    description: 'بطاقة مدرسية ذكية للعام الحالي تحتوي على الشريحة الذكية.',
    secretQuestion: 'ما هو الرقم التعريفي الأخير في البطاقة؟',
    secretAnswer: '4826',
    custody: 'at_office',
    status: 'open',
    reportedBy: DEMO_USERS[1], // Moshira
    createdAt: '2026-08-29T17:00:00.000Z',
  },
];

// ========================================================
// INTEGRITY AMBASSADOR MODULE CONSTANTS & SCENARIOS
// ========================================================

export const INTEGRITY_COOLDOWN_MS = 24 * 60 * 60 * 1000; // 24 Hours
export const INTEGRITY_PASSING_THRESHOLD = 90; // 90% or above required to pass
export const INTEGRITY_AWARD_POINTS = 10; // 10 Goodwill points per scenario passed

export const INTEGRITY_SCENARIOS: IntegrityScenario[] = [
  // 1. Academic Integrity / Exam Room (الغش الأكاديمي)
  {
    id: 'scenario_academic_integrity',
    title: 'النزاهة الأكاديمية: قاعة الاختبار وضغط الزميل',
    topicTitle: 'الغش الأكاديمي',
    shortDescription: 'طلب صديق مقرب إجابة سؤال مصيري في الاختبار النهائي أثناء انشغال المراقب.',
    detailedDilemma: 'أثناء سير الاختبار النهائي في مادة الرياضيات، انشغل المراقب بتوزيع الأوراق الإضافية، فالتفت إليك صديقك المقرب متوسلاً أن تهمس له بإجابة السؤال الثالث المصيري، مهدداً بأن رسوبه سينهي صداقتكما.',
    dilemmaQuote: 'صاحبك يهمس: "ساعدني في السؤال الثالث بسرعة قبل ما يلتفت المراقب.. إذا ما ساعدتني الحين لا تعتبرني صاحبك!"',
    cognitiveBasis: 'العلاج المعرفي السلوكي CBT - آرون بيك (تصحيح التشوهات الإدراكية ومقاومة ضغط الأقران)',
    visualDetails: {
      locationBadge: 'قاعة الاختبارات',
      roomLabel: 'قاعة 302',
      promptNote: '⚠️ ورقة اختبار أكاديمي - صاحبك: "ساعدني بسرعة!"',
      sceneImageUrl: '/images/scenarios/scenario_academic_integrity.jpg',
    },
    locationId: 'classrooms_g1',
    duration: '0:45',
    badgeName: 'سفير الشرف الأكاديمي',
    pointsAwarded: INTEGRITY_AWARD_POINTS,
    questions: [
      {
        id: 'academic_q1',
        order: 1,
        question: 'ما هو قرارك وتصرفك في هذا الموقف؟',
        explanation: 'النزاهة الأكاديمية تحمي العدالة وتكافؤ الفرص، والصداقة الحقيقية لا تبنى على كسر الأمانة.',
        options: [
          {
            id: 'academic_opt_1',
            text: 'التزام الصمت والتركيز في ورقتك ورفض تمرير الإجابة، ثم توضيح موقفك الأخلاقي له بهدوء بعد انتهاء الاختبار.',
            score: 100,
            feedback: 'تصرف بطولي ونموذجي! حماية النزاهة الأكاديمية تضمن العدالة وتكافؤ الفرص وتساعد زميلك على الاعتماد على نفسه مستقبلاً.',
            whyWrong: '',
            correctActionText: 'التركيز في ورقتك ورفض المشاركة في الغش يحمي عدالتك وعدالة زملائك، والوفاء للصداقة الحقيقية يكون بالتعاون في المذاكرة وليس في قاعة الامتحان.',
          },
          {
            id: 'academic_opt_2',
            text: 'كتابة رأس الخيط أو تلميح بسيط على مسودة وتمريرها له سريعاً لتفادي غضبه وتخفيف شعورك بالذنب.',
            score: 50,
            feedback: 'تعاطف مشوه وخاطئ؛ تقديم مساعدة غير مشروعة يجعلك شريكاً مباشراً في انتهاك العدالة وتكافؤ الفرص.',
            whyWrong: 'الاستجابة لضغط الأقران والتعاطف المشوه يجعلك شريكاً مباشراً في انتهاك العدالة وتكافؤ الفرص ويعرضك للعقوبة.',
            correctActionText: 'الرفض القاطع لأي شكل من أشكال الغش، لأن المساعدة الحقيقية تسبق الامتحان وليست بكسر الأمانة.',
          },
          {
            id: 'academic_opt_3',
            text: 'الصراخ في وجهه بصوت عالٍ وسط القاعة وإخبار المراقب فوراً لإحراجه أمام الطلاب.',
            score: 0,
            feedback: 'رد فعل انفعالي متسرع يربك القاعة ويزيد التوتر دون تحقيق التوجيه التربوي السليم.',
            whyWrong: 'إثارة الفوضى في قاعة الامتحان تصرف غير حكيم يشتت بقية الطلاب ويحول الموقف إلى نزاع شخصي.',
            correctActionText: 'التصرف بحزم وثبات وهدوء برفض التجاوب، وترك إدارة النظام للمراقب دون إحداث فوضى.',
          },
          {
            id: 'academic_opt_4',
            text: 'إعطاؤه ورقة إجابتك كاملة لينقل منها بحجة نصرة الصديق والوفاء له في الأوقات الصعبة.',
            score: 0,
            feedback: 'خيانة صريحة للأمانة العلمية وخرق صارخ لأنظمة الاختبارات يعرض كلاكما للرسوب.',
            whyWrong: 'خيانة صريحة للأمانة وتدمير لمبدأ العدالة وتكافؤ الفرص، ويعرض كلاكما للحرمان الأكاديمي.',
            correctActionText: 'النزاهة الأكاديمية خط أحمر لا يقبل المساومة، ومساعدة الصديق تكون بالمذاكرة سوياً قبل الاختبار.',
          },
        ],
      },
    ],
  },

  // 2. Digital Privacy / Unlocked Phone in hallway (الخصوصية الرقمية)
  {
    id: 'scenario_hallway_phone',
    title: 'الخصوصية الرقمية: هاتف مفتوح في الممر المدرسي',
    topicTitle: 'الخصوصية الرقمية',
    shortDescription: 'العثور على هاتف ذكي مفتوح القفل على مقعد الاستراحة بالممر يعرض رسائل ومحادثات خاصة.',
    detailedDilemma: 'وجدت هاتفاً ذكياً حديثاً ملقى على مقعد الممر المدرسي والشاشة مضاءة وغير مقفلة برمز سري وتظهر محادثات وصور خاصة. كيف تتعامل مع الموقف باحترافية وأمانة رقمية؟',
    dilemmaQuote: 'شاشة مضاءة تعرض محادثات خاصة: "الهاتف مفتوح وبإمكاني تصفح كل شيء دون أن يدري أحد.. ماذا أفعل؟"',
    cognitiveBasis: 'نظرية التطور الأخلاقي - لورنس كولبرغ (المستوى ما بعد التقليدي: المبادئ الأخلاقية وحرمة الخصوصية)',
    visualDetails: {
      locationBadge: 'الممر المدرسي',
      roomLabel: 'استراحة الطابق الأول',
      promptNote: '📱 هاتف ذكي مضاء وغير مقفل على المقعد',
      sceneImageUrl: '/images/scenarios/scenario_hallway_phone.jpg',
    },
    locationId: 'classrooms_g1',
    duration: '0:40',
    badgeName: 'حامي الخصوصية الرقمية',
    pointsAwarded: INTEGRITY_AWARD_POINTS,
    questions: [
      {
        id: 'phone_q1',
        order: 1,
        question: 'ما هو قرارك وتصرفك في هذا الموقف؟',
        explanation: 'الخصوصية الرقمية حق مصان؛ عدم التلصص والقفل الفوري هو جوهر المواطنة الرقمية.',
        options: [
          {
            id: 'phone_opt_1',
            text: 'قفل الشاشة فوراً دون تصفح أي بيانات، وتسليم الهاتف لإدارة المدرسة مع رفع بلاغ عبر FindIt لتسهيل مطابقته.',
            score: 100,
            feedback: 'قمة الوعي والأمانة الرقمية! احترام خصوصية الآخرين مبدأ أخلاقي راسخ يعزز الثقة والأمان في المدرسة.',
            whyWrong: '',
            correctActionText: 'القفل الفوري يحمي خصوصية الزميل، وتسليمه عبر القنوات المعتمدة مع توثيقه في FindIt يضمن عودته السريعة دون أي شبهات.',
          },
          {
            id: 'phone_opt_2',
            text: 'فتح سجل المكالمات والاتصال بآخر رقم لإبلاغه بمكان الهاتف قبل تسليمه للإدارة.',
            score: 50,
            feedback: 'النية حسنة، لكن الاطلاع على سجل الاتصالات ينتهك الخصوصية وقد يسبب إحراجاً لصاحب الهاتف.',
            whyWrong: 'الاطلاع على سجلات الهاتف وسيلة قد تبدو بريئة لكنها تنتهك خصوصية صاحب الهاتف دون إذنه.',
            correctActionText: 'تسليم الهاتف مغلقاً للإدارة واستخدام محرك FindIt الذكي للمطابقة دون تصفح محتويات الجهاز.',
          },
          {
            id: 'phone_opt_3',
            text: 'تصوير شاشة المحادثات بهاتفك ونشرها في مجموعات الطلاب للبحث عن صاحب الهاتف.',
            score: 0,
            feedback: 'تصرف خاطئ جداً؛ نشر الصور والبيانات الشخصية ينتهك النظام ويفضح خصوصية صاحب الهاتف.',
            whyWrong: 'نشر لقطات الشاشة في المجموعات يعرض البيانات الخاصة للانتشار وينتهك حرمة الحياة الخاصة للزميل.',
            correctActionText: 'حفظ خصوصية الآخرين واجب مدرسي ونظامي؛ عدم نشر أي بيانات شخصية والاكتفاء بالوصف الخارجي.',
          },
          {
            id: 'phone_opt_4',
            text: 'تصفح المعرض والمحادثات بدافع الفضول لمعرفة أسرار الزميل ومشاركتها مع أصدقائك.',
            score: 0,
            feedback: 'انتهاك صارخ لخصوصية الزملاء وسلوك غير أخلاقي يستوجب المساءلة التأديبية.',
            whyWrong: 'التجسس وتتبع عورات الآخرين خيانة جسيمة للأمانة وسلوك يتنافى مع الأخلاق والقيم المدرسية.',
            correctActionText: 'كف البصر عن خصوصيات الغير؛ فالأمانة الرقمية تبدأ بحفظ ما لا يحق لك الاطلاع عليه.',
          },
        ],
      },
    ],
  },

  // 3. Financial Honesty / Extra Cafeteria Change (الأمانة المالية والمصروف)
  {
    id: 'scenario_cafeteria_change',
    title: 'الأمانة المالية: خطأ باقي الحساب في المقصف',
    topicTitle: 'الأمانة المالية والمصروف',
    shortDescription: 'أعاد لك أمين الصندوق في الكافتيريا مبلغاً زائداً بالخطأ أثناء الزحام الشديد.',
    detailedDilemma: 'أثناء شراء وجبة الإفطار في طابور الكافتيريا المزدحم، أعطاك المحاسب بالخطأ ورقة نقدية فئة خمسين جنيهاً بدلاً من خمسة جنيهات ولم ينتبه لذلك وسط الضغط. كيف يكون تصرفك الأخلاقي؟',
    dilemmaQuote: 'المحاسب أعطاك خمسين جنيهاً بدلاً من خمسة جنيهات: "غلطة المحاسب وهو لم ينتبه، والمال أصبح في جيبي!"',
    cognitiveBasis: 'نظرية المحاسبة الذاتية والنزاهة المؤسسية (غرس الرقابة الذاتية والضمير الحي)',
    visualDetails: {
      locationBadge: 'كافتيريا المدرسة',
      roomLabel: 'منفذ البيع رقم 1',
      promptNote: '💵 باقي الحساب: ورقة خمسين جنيهاً زائدة بالخطأ',
      sceneImageUrl: '/images/scenarios/scenario_cafeteria_change.jpg',
    },
    locationId: 'cafeteria',
    duration: '0:40',
    badgeName: 'سفير النزاهة المالية',
    pointsAwarded: INTEGRITY_AWARD_POINTS,
    questions: [
      {
        id: 'cafeteria_q1',
        order: 1,
        question: 'ما هو قرارك وتصرفك في هذا الموقف؟',
        explanation: 'النزاهة المالية تنبع من الضمير الحي وإبراء الذمة فوراً دون تردد لحفظ حقوق العاملين.',
        options: [
          {
            id: 'cafeteria_opt_1',
            text: 'تنبيه المحاسب فوراً بلباقة وإعادة المبلغ الزائد إليه في الحال، لأن الأمانة تبدأ من النفس.',
            score: 100,
            feedback: 'أحسنت صنعاً! النزاهة المالية في اللحظات العفوية تعكس قوة الضمير ورقي التربية وتمنع اقتطاع النقص من راتب العامل.',
            whyWrong: '',
            correctActionText: 'المبادرة الفورية بإرجاع الحق لأهله تمنع تحميل العامل البسيط خسارة من راتبه وتجسد قمة النزاهة والضمير الحي.',
          },
          {
            id: 'cafeteria_opt_2',
            text: 'أخذ المبلغ والتصدق به لاحقاً في صندوق التبرعات بالمدرسة بحجة فعل الخير.',
            score: 50,
            feedback: 'تصرف في غير محله؛ الصدقة لا تجوز من مال الغير، وحق المحاسب أولى بالسداد لتفادي نقصه من راتبه.',
            whyWrong: 'الصدقة بمال لا تملكه تصرف باطل، وتسبب نقصاً في صندوق المحاسب يتحمله من جيبه الخاص.',
            correctActionText: 'إعادة المال لصاحبه أو المسؤول عن الصندوق مباشرة؛ فالأمانة ورد الحقوق مقدم على التبرع بمال الغير.',
          },
          {
            id: 'cafeteria_opt_3',
            text: 'الانتظار حتى نهاية اليوم الدراسي، وإعادة المبلغ فقط إذا اشتكى المحاسب من وجود عجز وبحث عنه.',
            score: 0,
            feedback: 'تردد غير مبرر؛ المماطلة في أداء الحقوق تفتح باب النسيان والتفريط في الأمانة.',
            whyWrong: 'تأخير أداء الحقوق والمماطلة فيها تسويف يعرض الأمانة للضياع والنسيان ويخالف الصدق.',
            correctActionText: 'إبراء الذمة واجب فوري ومباشر عند اكتشاف الخطأ دون انتظار مطالبة الآخرين بحقوقهم.',
          },
          {
            id: 'cafeteria_opt_4',
            text: 'وضع المبلغ في جيبك واستغلاله في شراء أطعمة إضافية بحجة أنه رزق ساقه الله إليك بسبب إهمال المحاسب.',
            score: 0,
            feedback: 'خيانة واضحة للأمانة واستحلال لمال الغير بدون وجه حق تحت مبررات زائفة.',
            whyWrong: 'استحلال أموال الآخرين واغتنام غفلتهم ضعف في الأمانة واستسهال لأكل أموال الناس بالباطل.',
            correctActionText: 'المال الحرام لا يبارك فيه، والواجب رد الزيادة فوراً لمن أخطأ في إعطائها.',
          },
        ],
      },
    ],
  },

  // 4. Responsibility & Courage in admitting damage in Computer Lab (المسؤولية والشجاعة)
  {
    id: 'scenario_computer_lab_damage',
    title: 'المسؤولية والشجاعة: تلف عرضي في معمل التقنية',
    topicTitle: 'المسؤولية والشجاعة',
    shortDescription: 'سقوط غير مقصود لشاشة حاسوب أثناء الحركة في المعمل دون وجود أحد.',
    detailedDilemma: 'أثناء تحركك في معمل الحاسب الآلي، تعثر سلك شاشة أحد الأجهزة بحقيبتك مما تسبب بسقوطها وتصدعها. كنت بمفردك في تلك الزاوية ولا يوجد كاميرات موجهة نحوك.',
    dilemmaQuote: 'شاشة الحاسوب تصدعت بعد تعثر السلك: "لا أحد رآني.. إذا اعترفت سأتعرض للمساءلة أو دفع القيمة!"',
    cognitiveBasis: 'نظرية التعلم الاجتماعي وتأكيد الذات - ألبرت باندورا (الشجاعة الأدبية وتحمل التبعات)',
    visualDetails: {
      locationBadge: 'معمل الحاسب الآلي',
      roomLabel: 'محطة العمل 14',
      promptNote: '🖥️ شاشة حاسوب متصدعة إثر تعثر السلك بالحقيبة',
      sceneImageUrl: '/images/scenarios/scenario_computer_lab_damage.jpg',
    },
    locationId: 'computer_lab',
    duration: '0:50',
    badgeName: 'رائد الشجاعة والمسؤولية',
    pointsAwarded: INTEGRITY_AWARD_POINTS,
    questions: [
      {
        id: 'comp_q1',
        order: 1,
        question: 'ما هو قرارك وتصرفك في هذا الموقف؟',
        explanation: 'الشجاعة الأدبية والاعتراف بالخطأ تمنع الظلم وتجسد الصدق الحقيقي.',
        options: [
          {
            id: 'comp_opt_1',
            text: 'التوجه الفوري لمعلم الحاسب أو إدارة المدرسة والاعتراف بالخطأ العرضي بشجاعة ومسؤولية مع عرض المساعدة في الإصلاح.',
            score: 100,
            feedback: 'قمة الشجاعة والنزاهة! الاعتراف بالخطأ فضيلة ترفع قدرك وتكسبك احترام وتقدير الجميع وتمنع اتهام الأبرياء.',
            whyWrong: '',
            correctActionText: 'الاعتراف بالخطأ فضيلة وشجاعة تنال بها احترام الجميع، وتمنع ظلم الطلاب الأبرياء بافتراض التخريب العمد.',
          },
          {
            id: 'comp_opt_2',
            text: 'إعادة الشاشة إلى مكانها والتزام الصمت، ثم إخبار المعلم لاحقاً فقط إذا فتح تحقيقاً في الأمر.',
            score: 50,
            feedback: 'موقف متردد يفتقر للمبادرة والشجاعة الأدبية المطلوبة في المواطنة الصالحة.',
            whyWrong: 'إخفاء الحادثة وسلوك الانتظار يضعك في موضع ريبة ويؤخر صيانة التجهيزات المدرسية.',
            correctActionText: 'المبادرة الإيجابية والإفصاح الفوري دليل النضج والشجاعة الأخلاقية.',
          },
          {
            id: 'comp_opt_3',
            text: 'مغادرة المعمل بهدوء والتظاهر بعدم معرفة ما حدث لتجنب التوبيخ أو دفع التكاليف.',
            score: 0,
            feedback: 'هروب من المسؤولية؛ قد يتسبب ذلك في اتهام طلاب أبرياء أو تضرر سير الحصص العملية.',
            whyWrong: 'الهروب من تبعات التصرفات ضعف شخصية، وقد يؤدي لاتهام زملاء أبرياء بالخطأ.',
            correctActionText: 'تحمل المسؤولية يعزز الثقة بالنفس، والخطأ العارض يُعالج بالصدق لا بالهروب والتنصل.',
          },
          {
            id: 'comp_opt_4',
            text: 'اتهام طالب آخر أو ادعاء أن الجهاز كان معطلاً ومكسوراً قبل دخولك لتبرئة نفسك.',
            score: 0,
            feedback: 'سلوك ظالم وخيانة للضمير؛ رمي التهم على الأبرياء يضاعف الخطأ ويجلب العقوبة.',
            whyWrong: 'الكذب والافتراء على الآخرين ظلم جسيم يضاعف الخطأ ويجلب العقوبات الإدارية والمساءلة الأخلاقية.',
            correctActionText: 'الصدق منجاة ودرع أمان؛ الشهامة تقتضي أن لا تحمل غيرك أخطاءك الشخصية أبداً.',
          },
        ],
      },
    ],
  },

  // 5. High-Value Lost Item / Science Lab Calculator (أمانة المقتنيات الثمينة)
  {
    id: 'scenario_science_lab_calc',
    title: 'أمانة المقتنيات الثمينة: حاسبة علمية متطورة في المعمل',
    topicTitle: 'أمانة المقتنيات الثمينة',
    shortDescription: 'العثور على حاسبة كاسيو متطورة على طاولة التجارب بعد خروج الطلاب وقبل الاختبار بساعات.',
    detailedDilemma: 'أثناء تنظيف طاولة التجارب في معمل الكيمياء، وجدت حاسبة بيانية متطورة نسيها زميلك قبل اختبار الرياضيات النهائي بساعات. كيف تتصرف لضمان وصولها لصاحبها بأسرع وقت؟',
    dilemmaQuote: 'حاسبة علمية باهظة الثمن على الطاولة: "صاحبها يحتاجها للاختبار بعد ساعات.. كيف أساعده بأمانة؟"',
    cognitiveBasis: 'أخلاقيات الأمانة والرقابة الذاتية الإيجابية (تعزيز التكافل وحفظ حقوق المجتمع المدرسي)',
    visualDetails: {
      locationBadge: 'معمل الكيمياء والفيزياء',
      roomLabel: 'طاولة التجارب 3',
      promptNote: '🔬 حاسبة بيانية باهظة الثمن مفقودة قبل الامتحان',
      sceneImageUrl: '/images/scenarios/scenario_science_lab_calc.jpg',
    },
    locationId: 'science_lab',
    duration: '0:45',
    badgeName: 'حارس الأمانات العلمية',
    pointsAwarded: INTEGRITY_AWARD_POINTS,
    questions: [
      {
        id: 'calc_q1',
        order: 1,
        question: 'ما هو قرارك وتصرفك في هذا الموقف؟',
        explanation: 'التوثيق الرقمي الفوري عبر FindIt وتسليم العهدة يضمن حفظ حق صاحب الغرض واستعادته فوراً.',
        options: [
          {
            id: 'calc_opt_1',
            text: 'تسجيل بلاغ فوري "معثور عليه" عبر تطبيق FindIt مع تسليم الحاسبة لمشرف المعمل وتحديد رقم الطاولة بدقة.',
            score: 100,
            feedback: 'تصرف نموذجي ومثالي! التوثيق السريع يمنع ضياع المقتنيات ويُفعّل محرك المطابقة فوراً لإنقاذ زميلك قبل الاختبار.',
            whyWrong: '',
            correctActionText: 'التوثيق الرقمي الموثوق عبر FindIt مع تسليم العهدة يضمن وصول المقتنى لصاحبه قبل بدء امتحانه.',
          },
          {
            id: 'calc_opt_2',
            text: 'أخذ الحاسبة في حقيبتك والبحث عن صاحبها بنفسك بسؤال الطلاب في الفسحة دون تسجيل بلاغ رسمي.',
            score: 50,
            feedback: 'النية طيبة، لكن الاعتماد على البحث الفردي دون توثيق رسمي قد يؤخر عودة الأمانة لصاحبها قبل الاختبار.',
            whyWrong: 'البحث الفردي العشوائي دون تسجيل بلاغ رسمي قد يفوت على الزميل فرصة استعادة حاسبته قبل موعد اختباره.',
            correctActionText: 'الاستفادة من نظام FindIt الموحد يضمن سرعة التحقق عبر الأسئلة السرية وتأكيد الملكية الموثقة.',
          },
          {
            id: 'calc_opt_3',
            text: 'ترك الحاسبة على الطاولة على أمل أن يتذكر صاحبها ويعود لأخذها لاحقاً.',
            score: 0,
            feedback: 'تصرف سلبي ومخاطرة؛ ترك مقتنى ثمين في معمل مفتوح قد يعرضه للضياع أو التلف.',
            whyWrong: 'ترك مقتنى ثمين في مكان عام ومفتوح يعرضه للسرقة أو الضياع أثناء دخول أفواج أخرى من الطلاب.',
            correctActionText: 'الإيجابية والمبادرة بحفظ اللقطة وتسليمها للمسؤولين يمنع فقدان المقتنيات ويحفظ حقوق الزملاء.',
          },
          {
            id: 'calc_opt_4',
            text: 'الاحتفاظ بالحاسبة لنفسك واستخدامها في الاختبار بحجة أن صاحبها أهملها.',
            score: 0,
            feedback: 'سلوك غير نزيه وخيانة صريحة للأمانة وقيم المجتمع المدرسي.',
            whyWrong: 'الاستيلاء على ممتلكات الآخرين تحت مبرر إهمالهم هو خيانة واضحة للأمانة وسرقة صريحة.',
            correctActionText: 'حرمة مال المسلم لا تسقط بإهماله؛ حفظ الأمانة وردها لأصحابها هو جوهر المواطنة الحقة.',
          },
        ],
      },
    ],
  },
];

// ========================================================
// AUTHENTIC SCHOOL ACTIVITIES & VOLUNTEERING QUESTS
// ========================================================
export const SCHOOL_ACTIVITIES: SchoolActivity[] = [
  {
    id: 'act_break_custody',
    title: 'جولة أمانات الفسحة وتفقد الساحات',
    description: 'المرور على ساحات المدرسة والممرات بعد الفسحة للتأكد من عدم وجود متعلقات أو أدوات منسية وتسجيلها فوراً.',
    category: 'integrity',
    points: 25,
    verificationType: 'instant',
    iconName: 'ShieldCheck',
    badgeReward: 'badge_integrity_champion',
    targetLocationId: 'playground',
    estimatedMinutes: 15,
    frequency: 'daily',
  },
  {
    id: 'act_lab_assistance',
    title: 'مساعدة مشرف معمل العلوم وترتيب العهدة',
    description: 'المشاركة في جرد وتنظيم أدوات التجارب في معمل العلوم بعد الحصص العملية والتأكد من سلامتها.',
    category: 'academic_support',
    points: 30,
    verificationType: 'supervised',
    iconName: 'FlaskConical',
    badgeReward: 'badge_lab_guardian',
    targetLocationId: 'science_lab',
    estimatedMinutes: 20,
    frequency: 'weekly',
  },
  {
    id: 'act_library_books',
    title: 'تنظيم وإعادة كتب المكتبة المدرسية',
    description: 'مساعدة أمين المكتبة في إعادة الكتب المستعارة إلى أماكنها المخصصة وترتيب طاولات القراءة.',
    category: 'academic_support',
    points: 20,
    verificationType: 'instant',
    iconName: 'Library',
    badgeReward: 'badge_lab_guardian',
    targetLocationId: 'library',
    estimatedMinutes: 15,
    frequency: 'daily',
  },
  {
    id: 'act_eco_clean',
    title: 'حملة فرز ونظافة البيئة المدرسية المركزية',
    description: 'المبادرة بفرز وتدوير الأدوات والعلب البلاستيكية والمحافظة على النظافة العامة في المرافق المدرسية.',
    category: 'environment',
    points: 35,
    verificationType: 'supervised',
    iconName: 'Leaf',
    badgeReward: 'badge_eco_ambassador',
    targetLocationId: 'playground',
    estimatedMinutes: 25,
    frequency: 'weekly',
  },
  {
    id: 'act_integrity_ambassador',
    title: 'نشر ملصقات التوعية بالأمانة والمفقودات',
    description: 'تعليق ملصقات نقاط QR الإرشادية على أبواب القاعات وتوعية الزملاء بكيفية استرداد الأمانات عبر FindIt.',
    category: 'integrity',
    points: 40,
    verificationType: 'supervised',
    iconName: 'QrCode',
    badgeReward: 'badge_integrity_champion',
    targetLocationId: 'classrooms_g1',
    estimatedMinutes: 30,
    frequency: 'weekly',
  },
  {
    id: 'act_peer_tutoring',
    title: 'مبادرة مساعدة الزملاء في المذاكرة الصباحية',
    description: 'تقديم الدعم الأكاديمي وشرح المسائل الصعبة للزملاء في الطابور الصباحي أو أوقات الاستراحة.',
    category: 'volunteer',
    points: 30,
    verificationType: 'supervised',
    iconName: 'Users',
    badgeReward: 'badge_volunteer_star',
    targetLocationId: 'library',
    estimatedMinutes: 20,
    frequency: 'weekly',
  },
  {
    id: 'act_gym_organization',
    title: 'تنظيم وإحصاء أدوات الصالة الرياضية',
    description: 'المساعدة في ترتيب الكرات والمعدات الرياضية بعد حصص التربية البدنية والتأكد من عدم نسيان مقتنيات.',
    category: 'volunteer',
    points: 20,
    verificationType: 'instant',
    iconName: 'Dumbbell',
    badgeReward: 'badge_volunteer_star',
    targetLocationId: 'gym',
    estimatedMinutes: 15,
    frequency: 'weekly',
  },
  {
    id: 'act_prayer_room_care',
    title: 'العناية بالمصلى المدرسي وترتيب المصاحف',
    description: 'ترتيب المصاحف والسجاد بالمصلى المدرسي والتأكد من نظافة المكان وتوفير بيئة هادئة ونظيفة للجميع.',
    category: 'volunteer',
    points: 25,
    verificationType: 'instant',
    iconName: 'Moon',
    badgeReward: 'badge_volunteer_star',
    targetLocationId: 'prayer_room',
    estimatedMinutes: 10,
    frequency: 'daily',
  },
];

export const ACTIVITY_BADGES: ActivityBadge[] = [
  {
    id: 'badge_volunteer_star',
    title: 'نجم التطوع المدرسي',
    description: 'مُنحت للمساهمة الفعالة في الأنشطة والمبادرات التطوعية وخدمة مجتمع المدرسة.',
    icon: '🌟',
    requiredPoints: 50,
    category: 'volunteer',
  },
  {
    id: 'badge_lab_guardian',
    title: 'حارس المعامل والأدوات',
    description: 'مُنحت للتميز في تنظيم وإدارة عهدة المعامل والمكتبة والمرافق العلمية.',
    icon: '🔬',
    requiredPoints: 60,
    category: 'academic_support',
  },
  {
    id: 'badge_eco_ambassador',
    title: 'سفير البيئة والنظام',
    description: 'مُنحت للريادة في مبادرات الحفاظ على البيئة المدرسية والنظافة العامة.',
    icon: '🌿',
    requiredPoints: 70,
    category: 'environment',
  },
  {
    id: 'badge_integrity_champion',
    title: 'قائد مبادرات الأمانة',
    description: 'مُنحت للجهود المتميزة في حماية الأمانات والتوعية الميدانية بثقافة النزاهة.',
    icon: '🎖️',
    requiredPoints: 80,
    category: 'integrity',
  },
];

export const INITIAL_ACTIVITY_SUBMISSIONS: ActivitySubmission[] = [
  {
    id: 'sub_init_1',
    activityId: 'act_lab_assistance',
    userId: 'student_finder_sara',
    userName: 'سارة القحطاني',
    userGrade: 'الصف العاشر - أ',
    status: 'approved',
    submittedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    notes: 'المساعدة في جرد أنابيب الاختبار وتنظيم عهدة معمل الكيمياء.',
    locationId: 'science_lab',
    awardedPoints: 30,
    reviewedBy: 'م. مشيرة',
    reviewedAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'sub_init_2',
    activityId: 'act_library_books',
    userId: 'user_malak',
    userName: 'ملك محمد فروق',
    userGrade: 'الصف الحادي عشر - علمي',
    status: 'approved',
    submittedAt: new Date(Date.now() - 86400000).toISOString(),
    notes: 'إعادة كتب الرياضيات والفيزياء المستعارة لرفوف القسم العلمي.',
    locationId: 'library',
    awardedPoints: 20,
    reviewedBy: 'النظام الذكي (فوري)',
    reviewedAt: new Date(Date.now() - 86400000).toISOString(),
  },
];

